name: "CrowdStrike Container Image Scan"
description: "Scan your container image for vulnerabilities and malware"
author: "The CrowdStrike Community"
branding:
  color: red
  icon: shield
inputs:
  falcon_client_id:
    description: "Your CrowdStrike OAUTH2 Client ID"
    required: true
  container_repository:
    description: "The container image to scan (e.g. my_image or myregistry.io/my_container)"
    required: true
  container_tag:
    description: "The container tag to scan against (default: latest)"
    default: latest
  crowdstrike_region:
    description: "The CrowdStrike Cloud region to submit for scanning (default: us-1)"
    default: us-1
  crowdstrike_score:
    description: "Vulnerability score threshold"
    default: 500
  retry_count:
    description: "Scan report download retries"
    default: 10
  log_level:
    description: "Set the logging level (default: INFO)"
    default: INFO
  json_report:
    description: "Export JSON report to specified file (Default: None)"
outputs:
  exit-code:
    description: "exit code of scan"
    value: ${{ steps.scan-image.outputs.exit-code }}

runs:
  using: composite
  steps:
    - run: "PIP_BREAK_SYSTEM_PACKAGES=1 pip install -r https://raw.githubusercontent.com/CrowdStrike/container-image-scan/main/requirements.txt"
      shell: bash
    - id: scan-image
      run: $GITHUB_ACTION_PATH/scan.sh -u '${{ inputs.falcon_client_id }}' -r '${{ inputs.container_repository }}' -t '${{ inputs.container_tag }}' -c '${{ inputs.crowdstrike_region }}' -s '${{ inputs.crowdstrike_score }}' -R '${{ inputs.retry_count }}' --log-level '${{ inputs.log_level }}' --json-report '${{ inputs.json_report }}'
      shell: bash
